on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  Buld:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    name: Builds llvm-cbe
    steps:
    - name: Docker Setup and Build
      uses: aminya/llvm-cbe@v8
    - name: Go to llvm root
      run: cd /root/llvm/
    - name: Upload all
      uses: actions/upload-artifact@v2-preview
      with:
        path: ./

  Skip:
    if: "!contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI ðŸš«
        run: echo skip ci
